language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - nvm install node
  - npm install -g solhint
before_script:
  - python -m solc.install v0.4.19
  - export SOLC_BINARY=$HOME/.py-solc/solc-v0.4.19/bin/solc
  - export LD_LIBRARY_PATH=$HOME/.py-solc/solc-v0.4.19/bin
script:
  - pytest
  - flake8
  - pwd
  - solhint solidity/contracts/*.sol
notifications:
  email: false
