version: 2
jobs:
  build:
    working_directory: ~/contracts
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "Install"
          command: |
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: "Test"
          command: |
            source venv/bin/activate
            pytest
      - run:
          name: "Lint"
          command: |
            source venv/bin/activate
            flake8